version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    volumes:
      - data:/data
    ports:
    - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=raspi:ras.pi:6379,local:redis:6379
    ports:
    - "8081:8081"
volumes:
  data: